### ISSUE TITLE
Logging Twice of EnterCardScreen when loading the app

### ISSUE THREAD

**Issue by haytham918** [educational-technology-collective/Space-Repetition-Ionic#19]
When we jump from the loading screen to the card screen, it will log the event twice. Right now, in our logging function, we just check if the previous event is EnterCardScreen. If it is, we will not log it again.

**Comment by LukeAnger** [comment]
This was due to a setState(prevState => {prevState.array.push(item); return prevState}) duplication bug. 

Fixed by using ES6 spread syntax instead:
setState({ . . . object, array: [ . . . object.array, item]})
